
/*
 * This file was generated by the SOM Compiler.
 * FileName: H:\ZIPZAP\WPSDLL\zipzap.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 *    ZIPZAP.IDL - A WorkFrame/2* Quickstart WPS/SOM application
 */


#ifndef SOM_zipzapfile_h
#define SOM_zipzapfile_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef zipzapfile
#define zipzapfile SOMObject
#endif
#include <wpdataf.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_zipzapfile
    #define M_zipzapfile SOMObject
#endif /* M_zipzapfile */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef WPRootFolder
    #define WPRootFolder SOMObject
#endif /* WPRootFolder */
#ifndef M_WPDisk
    #define M_WPDisk SOMObject
#endif /* M_WPDisk */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_WPRootFolder
    #define M_WPRootFolder SOMObject
#endif /* M_WPRootFolder */
#ifndef M_zipzapfolder
    #define M_zipzapfolder SOMObject
#endif /* M_zipzapfolder */

/*
 * End of user-defined types.
 */

#define zipzapfile_MajorVersion 1
#define zipzapfile_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define zipzapfileNewClass zipzapfilec
#pragma linkage(zipzapfilec, system)
#define zipzapfileClassData zipzapfiled
#define zipzapfileCClassData zipzapfilex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <zipzap.h>
/*--------------Migration------------*/
#define zipzapfile_classObj zipzapfileClassData.classObject
#define _zipzapfile zipzapfile_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK zipzapfileNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(zipzapfileNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct zipzapfileClassDataStructure {
	SOMClass *classObject;
} SOMDLINK zipzapfileClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct zipzapfileCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK zipzapfileCClassData;

/*
 * New and Renew macros for zipzapfile
 */
#define zipzapfileNew() \
   (_somNew(_zipzapfile ? _zipzapfile : zipzapfileNewClass(zipzapfile_MajorVersion, zipzapfile_MinorVersion)))
#define zipzapfileRenew(buf) \
   (_somRenew(_zipzapfile ? _zipzapfile : zipzapfileNewClass(zipzapfile_MajorVersion, zipzapfile_MinorVersion), buf))

/*
 * Override method: wpViewObject
 */
#define zipzapfile_wpViewObject(somSelf,hwndCnr,ulView,param) \
	WPObject_wpViewObject(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpDrop
 */
#define zipzapfile_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Override method: wpDragOver
 */
#define zipzapfile_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpModifyPopupMenu
 */
#define zipzapfile_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define zipzapfile_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpSetIcon
 */
#define zipzapfile_wpSetIcon(somSelf,hptrNewIcon) \
	WPObject_wpSetIcon(somSelf,hptrNewIcon)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define zipzapfile_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define zipzapfile_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define zipzapfile_wpPrintPifFile WPDataFile_wpPrintPifFile
#define zipzapfile_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define zipzapfile_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define zipzapfile_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define zipzapfile_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define zipzapfile_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define zipzapfile_wpSetRealName WPFileSystem_wpSetRealName
#define zipzapfile_wpSetType WPFileSystem_wpSetType
#define zipzapfile_wpQueryType WPFileSystem_wpQueryType
#define zipzapfile_wpSetAttr WPFileSystem_wpSetAttr
#define zipzapfile_wpQueryAttr WPFileSystem_wpQueryAttr
#define zipzapfile_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define zipzapfile_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define zipzapfile_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define zipzapfile_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define zipzapfile_wpQueryCreation WPFileSystem_wpQueryCreation
#define zipzapfile_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define zipzapfile_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define zipzapfile_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define zipzapfile_wpQueryEASize WPFileSystem_wpQueryEASize
#define zipzapfile_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define zipzapfile_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define zipzapfile_wpRefresh WPFileSystem_wpRefresh
#define zipzapfile_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define zipzapfile_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define zipzapfile_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define zipzapfile_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define zipzapfile_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define zipzapfile_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define zipzapfile_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define zipzapfile_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define zipzapfile_wpQueryRealName WPFileSystem_wpQueryRealName
#define zipzapfile_wpQueryFilename WPFileSystem_wpQueryFilename
#define zipzapfile_wpQueryDisk WPFileSystem_wpQueryDisk
#define zipzapfile_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define zipzapfile_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define zipzapfile_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define zipzapfile_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define zipzapfile_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define zipzapfile_wpAddSettingsPages WPObject_wpAddSettingsPages
#define zipzapfile_wpAddToObjUseList WPObject_wpAddToObjUseList
#define zipzapfile_wpAllocMem WPObject_wpAllocMem
#define zipzapfile_wpAppendObject WPObject_wpAppendObject
#define zipzapfile_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define zipzapfile_wpClose WPObject_wpClose
#define zipzapfile_wpCnrInsertObject WPObject_wpCnrInsertObject
#define zipzapfile_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define zipzapfile_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define zipzapfile_wpConfirmDelete WPObject_wpConfirmDelete
#define zipzapfile_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define zipzapfile_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define zipzapfile_wpCopyObject WPObject_wpCopyObject
#define zipzapfile_wpCreateAnother WPObject_wpCreateAnother
#define zipzapfile_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define zipzapfile_wpCreateShadowObject WPObject_wpCreateShadowObject
#define zipzapfile_wpDelete WPObject_wpDelete
#define zipzapfile_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define zipzapfile_wpDisplayHelp WPObject_wpDisplayHelp
#define zipzapfile_wpDisplayMenu WPObject_wpDisplayMenu
#define zipzapfile_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define zipzapfile_wpDraggedOverObject WPObject_wpDraggedOverObject
#define zipzapfile_wpDroppedOnObject WPObject_wpDroppedOnObject
#define zipzapfile_wpEndConversation WPObject_wpEndConversation
#define zipzapfile_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define zipzapfile_wpFindUseItem WPObject_wpFindUseItem
#define zipzapfile_wpFormatDragItem WPObject_wpFormatDragItem
#define zipzapfile_wpFree WPObject_wpFree
#define zipzapfile_wpFreeMem WPObject_wpFreeMem
#define zipzapfile_wpHide WPObject_wpHide
#define zipzapfile_wpInitData WPObject_wpInitData
#define zipzapfile_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define zipzapfile_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define zipzapfile_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define zipzapfile_wpMoveObject WPObject_wpMoveObject
#define zipzapfile_wpOpen WPObject_wpOpen
#define zipzapfile_wpPrintObject WPObject_wpPrintObject
#define zipzapfile_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define zipzapfile_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define zipzapfile_wpQueryConfirmations WPObject_wpQueryConfirmations
#define zipzapfile_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define zipzapfile_wpQueryDefaultView WPObject_wpQueryDefaultView
#define zipzapfile_wpQueryDetailsData WPObject_wpQueryDetailsData
#define zipzapfile_wpQueryError WPObject_wpQueryError
#define zipzapfile_wpSetFolder WPObject_wpSetFolder
#define zipzapfile_wpQueryFolder WPObject_wpQueryFolder
#define zipzapfile_wpQueryIcon WPObject_wpQueryIcon
#define zipzapfile_wpQueryIconData WPObject_wpQueryIconData
#define zipzapfile_wpQueryMinWindow WPObject_wpQueryMinWindow
#define zipzapfile_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define zipzapfile_wpQueryStyle WPObject_wpQueryStyle
#define zipzapfile_wpSetTaskRec WPObject_wpSetTaskRec
#define zipzapfile_wpFindTaskRec WPObject_wpFindTaskRec
#define zipzapfile_wpQueryTitle WPObject_wpQueryTitle
#define zipzapfile_wpRegisterView WPObject_wpRegisterView
#define zipzapfile_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define zipzapfile_wpRender WPObject_wpRender
#define zipzapfile_wpRenderComplete WPObject_wpRenderComplete
#define zipzapfile_wpReplaceObject WPObject_wpReplaceObject
#define zipzapfile_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define zipzapfile_wpRestore WPObject_wpRestore
#define zipzapfile_wpRestoreData WPObject_wpRestoreData
#define zipzapfile_wpRestoreLong WPObject_wpRestoreLong
#define zipzapfile_wpRestoreState WPObject_wpRestoreState
#define zipzapfile_wpRestoreString WPObject_wpRestoreString
#define zipzapfile_wpSaveData WPObject_wpSaveData
#define zipzapfile_wpSaveImmediate WPObject_wpSaveImmediate
#define zipzapfile_wpSaveDeferred WPObject_wpSaveDeferred
#define zipzapfile_wpSaveLong WPObject_wpSaveLong
#define zipzapfile_wpSaveState WPObject_wpSaveState
#define zipzapfile_wpSaveString WPObject_wpSaveString
#define zipzapfile_wpScanSetupString WPObject_wpScanSetupString
#define zipzapfile_wpSetConcurrentView WPObject_wpSetConcurrentView
#define zipzapfile_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define zipzapfile_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define zipzapfile_wpSetDefaultView WPObject_wpSetDefaultView
#define zipzapfile_wpSetError WPObject_wpSetError
#define zipzapfile_wpSetIconHandle WPObject_wpSetIconHandle
#define zipzapfile_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define zipzapfile_wpSetupOnce WPObject_wpSetupOnce
#define zipzapfile_wpSetIconData WPObject_wpSetIconData
#define zipzapfile_wpSetMinWindow WPObject_wpSetMinWindow
#define zipzapfile_wpSetStyle WPObject_wpSetStyle
#define zipzapfile_wpModifyStyle WPObject_wpModifyStyle
#define zipzapfile_wpSetTitle WPObject_wpSetTitle
#define zipzapfile_wpSetup WPObject_wpSetup
#define zipzapfile_wpSwitchTo WPObject_wpSwitchTo
#define zipzapfile_wpUnInitData WPObject_wpUnInitData
#define zipzapfile_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define zipzapfile_wpQueryHandle WPObject_wpQueryHandle
#define zipzapfile_wpUnlockObject WPObject_wpUnlockObject
#define zipzapfile_wpObjectReady WPObject_wpObjectReady
#define zipzapfile_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define zipzapfile_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define zipzapfile_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define zipzapfile_wpIsDeleteable WPObject_wpIsDeleteable
#define zipzapfile_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define zipzapfile_wpSetObjectID WPObject_wpSetObjectID
#define zipzapfile_wpQueryObjectID WPObject_wpQueryObjectID
#define zipzapfile_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define zipzapfile_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define zipzapfile_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define zipzapfile_wpFindViewItem WPObject_wpFindViewItem
#define zipzapfile_wpLockObject WPObject_wpLockObject
#define zipzapfile_wpIsLocked WPObject_wpIsLocked
#define zipzapfile_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define zipzapfile_wpWaitForClose WPObject_wpWaitForClose
#define zipzapfile_somDefaultInit SOMObject_somDefaultInit
#define zipzapfile_somDestruct SOMObject_somDestruct
#define zipzapfile_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define zipzapfile_somDefaultAssign SOMObject_somDefaultAssign
#define zipzapfile_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define zipzapfile_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define zipzapfile_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define zipzapfile_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define zipzapfile_somDefaultVAssign SOMObject_somDefaultVAssign
#define zipzapfile_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define zipzapfile_somInit SOMObject_somInit
#define zipzapfile_somFree SOMObject_somFree
#define zipzapfile_somUninit SOMObject_somUninit
#define zipzapfile_somGetClass SOMObject_somGetClass
#define zipzapfile_somGetClassName SOMObject_somGetClassName
#define zipzapfile_somGetSize SOMObject_somGetSize
#define zipzapfile_somIsA SOMObject_somIsA
#define zipzapfile_somIsInstanceOf SOMObject_somIsInstanceOf
#define zipzapfile_somRespondsTo SOMObject_somRespondsTo
#define zipzapfile_somDispatch SOMObject_somDispatch
#define zipzapfile_somClassDispatch SOMObject_somClassDispatch
#define zipzapfile_somCastObj SOMObject_somCastObj
#define zipzapfile_somResetObj SOMObject_somResetObj
#define zipzapfile_somDispatchV SOMObject_somDispatchV
#define zipzapfile_somDispatchL SOMObject_somDispatchL
#define zipzapfile_somDispatchA SOMObject_somDispatchA
#define zipzapfile_somDispatchD SOMObject_somDispatchD
#define zipzapfile_somPrintSelf SOMObject_somPrintSelf
#define zipzapfile_somDumpSelf SOMObject_somDumpSelf
#define zipzapfile_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_zipzapfile_h */

#ifndef SOM_M_zipzapfile_h
#define SOM_M_zipzapfile_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_zipzapfile
#define M_zipzapfile SOMObject
#endif
#include <wpdataf.h>

/*
 * Start of user-defined types:
 */
typedef
unsigned long  M_zipzapfile_HMODULE;
typedef
unsigned long  M_zipzapfile_HPOINTER;
typedef
string  M_zipzapfile_PSZ;

/*
 *  New class methods
 */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HMODULE
    #ifdef HMODULE
        #undef HMODULE
        #define SOMTGD_HMODULE 1
    #else
        #define HMODULE M_zipzapfile_HMODULE
    #endif /* HMODULE */
#endif /* SOMTGD_HMODULE */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HPOINTER
    #ifdef HPOINTER
        #undef HPOINTER
        #define SOMTGD_HPOINTER 1
    #else
        #define HPOINTER M_zipzapfile_HPOINTER
    #endif /* HPOINTER */
#endif /* SOMTGD_HPOINTER */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSZ
    #ifdef PSZ
        #undef PSZ
        #define SOMTGD_PSZ 1
    #else
        #define PSZ M_zipzapfile_PSZ
    #endif /* PSZ */
#endif /* SOMTGD_PSZ */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of user-defined types.
 */

#define M_zipzapfile_MajorVersion 1
#define M_zipzapfile_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_zipzapfileNewClass zipzapfilec
#pragma linkage(zipzapfilec, system)
#define M_zipzapfileClassData zipzapfiled
#define M_zipzapfileCClassData zipzapfilex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_zipzapfile_classObj M_zipzapfileClassData.classObject
#define _M_zipzapfile M_zipzapfile_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_zipzapfileNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_zipzapfileNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_zipzapfileClassDataStructure {
	SOMClass *classObject;
	somMToken _get_hmodResource;
	somMToken _set_hmodResource;
} SOMDLINK M_zipzapfileClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_zipzapfileCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_zipzapfileCClassData;

/*
 * New and Renew macros for M_zipzapfile
 */
#define M_zipzapfileNew() \
   (_somNew(_M_zipzapfile ? _M_zipzapfile : M_zipzapfileNewClass(M_zipzapfile_MajorVersion, M_zipzapfile_MinorVersion)))
#define M_zipzapfileRenew(buf) \
   (_somRenew(_M_zipzapfile ? _M_zipzapfile : M_zipzapfileNewClass(M_zipzapfile_MajorVersion, M_zipzapfile_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_zipzapfile_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_zipzapfile_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * New Method: _get_hmodResource
 */
typedef M_zipzapfile_HMODULE   SOMLINK somTP_M_zipzapfile__get_hmodResource(M_zipzapfile *somSelf);
#pragma linkage(somTP_M_zipzapfile__get_hmodResource, system)
typedef somTP_M_zipzapfile__get_hmodResource *somTD_M_zipzapfile__get_hmodResource;
#define somMD_M_zipzapfile__get_hmodResource "::M_zipzapfile::_get_hmodResource"
#define M_zipzapfile__get_hmodResource(somSelf) \
    (SOM_Resolve(somSelf, M_zipzapfile, _get_hmodResource) \
	(somSelf))
#ifndef SOMGD_get_hmodResource
    #if (defined(_get_hmodResource) || defined(__get_hmodResource))
        #undef _get_hmodResource
        #undef __get_hmodResource
        #define SOMGD_get_hmodResource 1
    #else
        #define __get_hmodResource M_zipzapfile__get_hmodResource
    #endif /* __get_hmodResource */
#endif /* SOMGD_get_hmodResource */

/*
 * New Method: _set_hmodResource
 */
typedef void   SOMLINK somTP_M_zipzapfile__set_hmodResource(M_zipzapfile *somSelf,
		M_zipzapfile_HMODULE hmodResource);
#pragma linkage(somTP_M_zipzapfile__set_hmodResource, system)
typedef somTP_M_zipzapfile__set_hmodResource *somTD_M_zipzapfile__set_hmodResource;
#define somMD_M_zipzapfile__set_hmodResource "::M_zipzapfile::_set_hmodResource"
#define M_zipzapfile__set_hmodResource(somSelf,hmodResource) \
    (SOM_Resolve(somSelf, M_zipzapfile, _set_hmodResource) \
	(somSelf,hmodResource))
#ifndef SOMGD_set_hmodResource
    #if (defined(_set_hmodResource) || defined(__set_hmodResource))
        #undef _set_hmodResource
        #undef __set_hmodResource
        #define SOMGD_set_hmodResource 1
    #else
        #define __set_hmodResource M_zipzapfile__set_hmodResource
    #endif /* __set_hmodResource */
#endif /* SOMGD_set_hmodResource */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_zipzapfile_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_zipzapfile_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_zipzapfile_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_zipzapfile_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_zipzapfile_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_zipzapfile_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_zipzapfile_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_zipzapfile_wpclsNew M_WPObject_wpclsNew
#define M_zipzapfile_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_zipzapfile_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_zipzapfile_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_zipzapfile_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_zipzapfile_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_zipzapfile_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_zipzapfile_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_zipzapfile_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_zipzapfile_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_zipzapfile_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_zipzapfile_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_zipzapfile_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_zipzapfile_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_zipzapfile_wpclsSetError M_WPObject_wpclsSetError
#define M_zipzapfile_wpclsQueryError M_WPObject_wpclsQueryError
#define M_zipzapfile_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_zipzapfile_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_zipzapfile_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_zipzapfile_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_zipzapfile_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_zipzapfile_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_zipzapfile_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_zipzapfile_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_zipzapfile_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_zipzapfile_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_zipzapfile_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_zipzapfile_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_zipzapfile_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_zipzapfile__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_zipzapfile__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_zipzapfile__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_zipzapfile__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_zipzapfile_somNew SOMClass_somNew
#define M_zipzapfile_somNewNoInit SOMClass_somNewNoInit
#define M_zipzapfile_somRenew SOMClass_somRenew
#define M_zipzapfile_somRenewNoInit SOMClass_somRenewNoInit
#define M_zipzapfile_somRenewNoZero SOMClass_somRenewNoZero
#define M_zipzapfile_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_zipzapfile_somAllocate SOMClass_somAllocate
#define M_zipzapfile_somDeallocate SOMClass_somDeallocate
#define M_zipzapfile__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_zipzapfile__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_zipzapfile_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_zipzapfile_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_zipzapfile_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_zipzapfile_somInitClass SOMClass_somInitClass
#define M_zipzapfile_somInitMIClass SOMClass_somInitMIClass
#define M_zipzapfile_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_zipzapfile_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_zipzapfile_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_zipzapfile_somClassReady SOMClass_somClassReady
#define M_zipzapfile_somGetApplyStub SOMClass_somGetApplyStub
#define M_zipzapfile_somGetClassData SOMClass_somGetClassData
#define M_zipzapfile_somSetClassData SOMClass_somSetClassData
#define M_zipzapfile_somGetClassMtab SOMClass_somGetClassMtab
#define M_zipzapfile_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_zipzapfile_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_zipzapfile_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_zipzapfile_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_zipzapfile_somGetMemberToken SOMClass_somGetMemberToken
#define M_zipzapfile_somGetMethodData SOMClass_somGetMethodData
#define M_zipzapfile_somGetRdStub SOMClass_somGetRdStub
#define M_zipzapfile_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_zipzapfile_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_zipzapfile_somGetMethodToken SOMClass_somGetMethodToken
#define M_zipzapfile_somGetName SOMClass_somGetName
#define M_zipzapfile_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_zipzapfile_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_zipzapfile_somGetNumMethods SOMClass_somGetNumMethods
#define M_zipzapfile_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_zipzapfile_somGetParent SOMClass_somGetParent
#define M_zipzapfile_somGetParents SOMClass_somGetParents
#define M_zipzapfile_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_zipzapfile_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_zipzapfile_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_zipzapfile_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_zipzapfile_somFindMethod SOMClass_somFindMethod
#define M_zipzapfile_somFindMethodOk SOMClass_somFindMethodOk
#define M_zipzapfile_somFindSMethod SOMClass_somFindSMethod
#define M_zipzapfile_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_zipzapfile_somLookupMethod SOMClass_somLookupMethod
#define M_zipzapfile_somCheckVersion SOMClass_somCheckVersion
#define M_zipzapfile_somDescendedFrom SOMClass_somDescendedFrom
#define M_zipzapfile_somSupportsMethod SOMClass_somSupportsMethod
#define M_zipzapfile_somDefinedMethod SOMClass_somDefinedMethod
#define M_zipzapfile_somOverrideMtab SOMClass_somOverrideMtab
#define M_zipzapfile_somDefaultInit SOMObject_somDefaultInit
#define M_zipzapfile_somDestruct SOMObject_somDestruct
#define M_zipzapfile_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_zipzapfile_somDefaultAssign SOMObject_somDefaultAssign
#define M_zipzapfile_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_zipzapfile_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_zipzapfile_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_zipzapfile_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_zipzapfile_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_zipzapfile_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_zipzapfile_somInit SOMObject_somInit
#define M_zipzapfile_somFree SOMObject_somFree
#define M_zipzapfile_somUninit SOMObject_somUninit
#define M_zipzapfile_somGetClass SOMObject_somGetClass
#define M_zipzapfile_somGetClassName SOMObject_somGetClassName
#define M_zipzapfile_somGetSize SOMObject_somGetSize
#define M_zipzapfile_somIsA SOMObject_somIsA
#define M_zipzapfile_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_zipzapfile_somRespondsTo SOMObject_somRespondsTo
#define M_zipzapfile_somDispatch SOMObject_somDispatch
#define M_zipzapfile_somClassDispatch SOMObject_somClassDispatch
#define M_zipzapfile_somCastObj SOMObject_somCastObj
#define M_zipzapfile_somResetObj SOMObject_somResetObj
#define M_zipzapfile_somDispatchV SOMObject_somDispatchV
#define M_zipzapfile_somDispatchL SOMObject_somDispatchL
#define M_zipzapfile_somDispatchA SOMObject_somDispatchA
#define M_zipzapfile_somDispatchD SOMObject_somDispatchD
#define M_zipzapfile_somPrintSelf SOMObject_somPrintSelf
#define M_zipzapfile_somDumpSelf SOMObject_somDumpSelf
#define M_zipzapfile_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_zipzapfile_h */

#ifndef SOM_zipzapfolder_h
#define SOM_zipzapfolder_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef zipzapfolder
#define zipzapfolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define zipzapfolder_MajorVersion 1
#define zipzapfolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define zipzapfolderNewClass zipzapc
#pragma linkage(zipzapc, system)
#define zipzapfolderClassData zipzapd
#define zipzapfolderCClassData zipzapx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <zipzap.h>
/*--------------Migration------------*/
#define zipzapfolder_classObj zipzapfolderClassData.classObject
#define _zipzapfolder zipzapfolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK zipzapfolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(zipzapfolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct zipzapfolderClassDataStructure {
	SOMClass *classObject;
} SOMDLINK zipzapfolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct zipzapfolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK zipzapfolderCClassData;

/*
 * New and Renew macros for zipzapfolder
 */
#define zipzapfolderNew() \
   (_somNew(_zipzapfolder ? _zipzapfolder : zipzapfolderNewClass(zipzapfolder_MajorVersion, zipzapfolder_MinorVersion)))
#define zipzapfolderRenew(buf) \
   (_somRenew(_zipzapfolder ? _zipzapfolder : zipzapfolderNewClass(zipzapfolder_MajorVersion, zipzapfolder_MinorVersion), buf))

/*
 * Override method: wpModifyPopupMenu
 */
#define zipzapfolder_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define zipzapfolder_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpOpen
 */
#define zipzapfolder_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define zipzapfolder_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define zipzapfolder_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define zipzapfolder_wpSetFldrFont WPFolder_wpSetFldrFont
#define zipzapfolder_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define zipzapfolder_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define zipzapfolder_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define zipzapfolder_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define zipzapfolder_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define zipzapfolder_wpPopulate WPFolder_wpPopulate
#define zipzapfolder_wpQueryContent WPFolder_wpQueryContent
#define zipzapfolder_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define zipzapfolder_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define zipzapfolder_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define zipzapfolder_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define zipzapfolder_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define zipzapfolder_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define zipzapfolder_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define zipzapfolder_wpInitIconPosData WPFolder_wpInitIconPosData
#define zipzapfolder_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define zipzapfolder_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define zipzapfolder_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define zipzapfolder_wpSetFldrSort WPFolder_wpSetFldrSort
#define zipzapfolder_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define zipzapfolder_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define zipzapfolder_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define zipzapfolder_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define zipzapfolder_wpDeleteContents WPFolder_wpDeleteContents
#define zipzapfolder_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define zipzapfolder_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define zipzapfolder_wpSearchFolder WPFolder_wpSearchFolder
#define zipzapfolder_wpContainsFolders WPFolder_wpContainsFolders
#define zipzapfolder_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define zipzapfolder_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define zipzapfolder_wpAddToContent WPFolder_wpAddToContent
#define zipzapfolder_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define zipzapfolder_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define zipzapfolder_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define zipzapfolder_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define zipzapfolder_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define zipzapfolder_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define zipzapfolder_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define zipzapfolder_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define zipzapfolder_wpAddFirstChild WPFolder_wpAddFirstChild
#define zipzapfolder_wpSetRealName WPFileSystem_wpSetRealName
#define zipzapfolder_wpSetType WPFileSystem_wpSetType
#define zipzapfolder_wpQueryType WPFileSystem_wpQueryType
#define zipzapfolder_wpSetAttr WPFileSystem_wpSetAttr
#define zipzapfolder_wpQueryAttr WPFileSystem_wpQueryAttr
#define zipzapfolder_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define zipzapfolder_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define zipzapfolder_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define zipzapfolder_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define zipzapfolder_wpQueryCreation WPFileSystem_wpQueryCreation
#define zipzapfolder_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define zipzapfolder_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define zipzapfolder_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define zipzapfolder_wpQueryEASize WPFileSystem_wpQueryEASize
#define zipzapfolder_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define zipzapfolder_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define zipzapfolder_wpRefresh WPFileSystem_wpRefresh
#define zipzapfolder_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define zipzapfolder_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define zipzapfolder_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define zipzapfolder_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define zipzapfolder_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define zipzapfolder_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define zipzapfolder_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define zipzapfolder_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define zipzapfolder_wpQueryRealName WPFileSystem_wpQueryRealName
#define zipzapfolder_wpQueryFilename WPFileSystem_wpQueryFilename
#define zipzapfolder_wpQueryDisk WPFileSystem_wpQueryDisk
#define zipzapfolder_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define zipzapfolder_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define zipzapfolder_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define zipzapfolder_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define zipzapfolder_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define zipzapfolder_wpAddSettingsPages WPObject_wpAddSettingsPages
#define zipzapfolder_wpAddToObjUseList WPObject_wpAddToObjUseList
#define zipzapfolder_wpAllocMem WPObject_wpAllocMem
#define zipzapfolder_wpAppendObject WPObject_wpAppendObject
#define zipzapfolder_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define zipzapfolder_wpClose WPObject_wpClose
#define zipzapfolder_wpCnrInsertObject WPObject_wpCnrInsertObject
#define zipzapfolder_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define zipzapfolder_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define zipzapfolder_wpConfirmDelete WPObject_wpConfirmDelete
#define zipzapfolder_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define zipzapfolder_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define zipzapfolder_wpCopyObject WPObject_wpCopyObject
#define zipzapfolder_wpCreateAnother WPObject_wpCreateAnother
#define zipzapfolder_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define zipzapfolder_wpCreateShadowObject WPObject_wpCreateShadowObject
#define zipzapfolder_wpDelete WPObject_wpDelete
#define zipzapfolder_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define zipzapfolder_wpDisplayHelp WPObject_wpDisplayHelp
#define zipzapfolder_wpDisplayMenu WPObject_wpDisplayMenu
#define zipzapfolder_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define zipzapfolder_wpDraggedOverObject WPObject_wpDraggedOverObject
#define zipzapfolder_wpDragOver WPObject_wpDragOver
#define zipzapfolder_wpDrop WPObject_wpDrop
#define zipzapfolder_wpDroppedOnObject WPObject_wpDroppedOnObject
#define zipzapfolder_wpEndConversation WPObject_wpEndConversation
#define zipzapfolder_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define zipzapfolder_wpFindUseItem WPObject_wpFindUseItem
#define zipzapfolder_wpFormatDragItem WPObject_wpFormatDragItem
#define zipzapfolder_wpFree WPObject_wpFree
#define zipzapfolder_wpFreeMem WPObject_wpFreeMem
#define zipzapfolder_wpHide WPObject_wpHide
#define zipzapfolder_wpInitData WPObject_wpInitData
#define zipzapfolder_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define zipzapfolder_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define zipzapfolder_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define zipzapfolder_wpMoveObject WPObject_wpMoveObject
#define zipzapfolder_wpPrintObject WPObject_wpPrintObject
#define zipzapfolder_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define zipzapfolder_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define zipzapfolder_wpQueryConfirmations WPObject_wpQueryConfirmations
#define zipzapfolder_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define zipzapfolder_wpQueryDefaultView WPObject_wpQueryDefaultView
#define zipzapfolder_wpQueryDetailsData WPObject_wpQueryDetailsData
#define zipzapfolder_wpQueryError WPObject_wpQueryError
#define zipzapfolder_wpSetFolder WPObject_wpSetFolder
#define zipzapfolder_wpQueryFolder WPObject_wpQueryFolder
#define zipzapfolder_wpQueryIcon WPObject_wpQueryIcon
#define zipzapfolder_wpQueryIconData WPObject_wpQueryIconData
#define zipzapfolder_wpQueryMinWindow WPObject_wpQueryMinWindow
#define zipzapfolder_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define zipzapfolder_wpQueryStyle WPObject_wpQueryStyle
#define zipzapfolder_wpSetTaskRec WPObject_wpSetTaskRec
#define zipzapfolder_wpFindTaskRec WPObject_wpFindTaskRec
#define zipzapfolder_wpQueryTitle WPObject_wpQueryTitle
#define zipzapfolder_wpRegisterView WPObject_wpRegisterView
#define zipzapfolder_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define zipzapfolder_wpRender WPObject_wpRender
#define zipzapfolder_wpRenderComplete WPObject_wpRenderComplete
#define zipzapfolder_wpReplaceObject WPObject_wpReplaceObject
#define zipzapfolder_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define zipzapfolder_wpRestore WPObject_wpRestore
#define zipzapfolder_wpRestoreData WPObject_wpRestoreData
#define zipzapfolder_wpRestoreLong WPObject_wpRestoreLong
#define zipzapfolder_wpRestoreState WPObject_wpRestoreState
#define zipzapfolder_wpRestoreString WPObject_wpRestoreString
#define zipzapfolder_wpSaveData WPObject_wpSaveData
#define zipzapfolder_wpSaveImmediate WPObject_wpSaveImmediate
#define zipzapfolder_wpSaveDeferred WPObject_wpSaveDeferred
#define zipzapfolder_wpSaveLong WPObject_wpSaveLong
#define zipzapfolder_wpSaveState WPObject_wpSaveState
#define zipzapfolder_wpSaveString WPObject_wpSaveString
#define zipzapfolder_wpScanSetupString WPObject_wpScanSetupString
#define zipzapfolder_wpSetConcurrentView WPObject_wpSetConcurrentView
#define zipzapfolder_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define zipzapfolder_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define zipzapfolder_wpSetDefaultView WPObject_wpSetDefaultView
#define zipzapfolder_wpSetError WPObject_wpSetError
#define zipzapfolder_wpSetIconHandle WPObject_wpSetIconHandle
#define zipzapfolder_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define zipzapfolder_wpSetupOnce WPObject_wpSetupOnce
#define zipzapfolder_wpSetIcon WPObject_wpSetIcon
#define zipzapfolder_wpSetIconData WPObject_wpSetIconData
#define zipzapfolder_wpSetMinWindow WPObject_wpSetMinWindow
#define zipzapfolder_wpSetStyle WPObject_wpSetStyle
#define zipzapfolder_wpModifyStyle WPObject_wpModifyStyle
#define zipzapfolder_wpSetTitle WPObject_wpSetTitle
#define zipzapfolder_wpSetup WPObject_wpSetup
#define zipzapfolder_wpSwitchTo WPObject_wpSwitchTo
#define zipzapfolder_wpUnInitData WPObject_wpUnInitData
#define zipzapfolder_wpViewObject WPObject_wpViewObject
#define zipzapfolder_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define zipzapfolder_wpQueryHandle WPObject_wpQueryHandle
#define zipzapfolder_wpUnlockObject WPObject_wpUnlockObject
#define zipzapfolder_wpObjectReady WPObject_wpObjectReady
#define zipzapfolder_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define zipzapfolder_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define zipzapfolder_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define zipzapfolder_wpIsDeleteable WPObject_wpIsDeleteable
#define zipzapfolder_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define zipzapfolder_wpSetObjectID WPObject_wpSetObjectID
#define zipzapfolder_wpQueryObjectID WPObject_wpQueryObjectID
#define zipzapfolder_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define zipzapfolder_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define zipzapfolder_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define zipzapfolder_wpFindViewItem WPObject_wpFindViewItem
#define zipzapfolder_wpLockObject WPObject_wpLockObject
#define zipzapfolder_wpIsLocked WPObject_wpIsLocked
#define zipzapfolder_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define zipzapfolder_wpWaitForClose WPObject_wpWaitForClose
#define zipzapfolder_somDefaultInit SOMObject_somDefaultInit
#define zipzapfolder_somDestruct SOMObject_somDestruct
#define zipzapfolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define zipzapfolder_somDefaultAssign SOMObject_somDefaultAssign
#define zipzapfolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define zipzapfolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define zipzapfolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define zipzapfolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define zipzapfolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define zipzapfolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define zipzapfolder_somInit SOMObject_somInit
#define zipzapfolder_somFree SOMObject_somFree
#define zipzapfolder_somUninit SOMObject_somUninit
#define zipzapfolder_somGetClass SOMObject_somGetClass
#define zipzapfolder_somGetClassName SOMObject_somGetClassName
#define zipzapfolder_somGetSize SOMObject_somGetSize
#define zipzapfolder_somIsA SOMObject_somIsA
#define zipzapfolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define zipzapfolder_somRespondsTo SOMObject_somRespondsTo
#define zipzapfolder_somDispatch SOMObject_somDispatch
#define zipzapfolder_somClassDispatch SOMObject_somClassDispatch
#define zipzapfolder_somCastObj SOMObject_somCastObj
#define zipzapfolder_somResetObj SOMObject_somResetObj
#define zipzapfolder_somDispatchV SOMObject_somDispatchV
#define zipzapfolder_somDispatchL SOMObject_somDispatchL
#define zipzapfolder_somDispatchA SOMObject_somDispatchA
#define zipzapfolder_somDispatchD SOMObject_somDispatchD
#define zipzapfolder_somPrintSelf SOMObject_somPrintSelf
#define zipzapfolder_somDumpSelf SOMObject_somDumpSelf
#define zipzapfolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_zipzapfolder_h */

#ifndef SOM_M_zipzapfolder_h
#define SOM_M_zipzapfolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_zipzapfolder
#define M_zipzapfolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */
typedef
unsigned long  M_zipzapfolder_HPOINTER;
typedef
string  M_zipzapfolder_PSZ;

/*
 *  New class methods
 *  HMODULE clsGetResourceModule();
 *  attribute HMODULE  hResource; //# Resource module handle for zipzapfolder
 *  attribute HPOINTER hMyIcon;      //# Icon handle for zipzapfolder
 *  attribute PSZ      pszMyTitle;   //# Title of this SOM object
 */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HPOINTER
    #ifdef HPOINTER
        #undef HPOINTER
        #define SOMTGD_HPOINTER 1
    #else
        #define HPOINTER M_zipzapfolder_HPOINTER
    #endif /* HPOINTER */
#endif /* SOMTGD_HPOINTER */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSZ
    #ifdef PSZ
        #undef PSZ
        #define SOMTGD_PSZ 1
    #else
        #define PSZ M_zipzapfolder_PSZ
    #endif /* PSZ */
#endif /* SOMTGD_PSZ */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of user-defined types.
 */

#define M_zipzapfolder_MajorVersion 1
#define M_zipzapfolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_zipzapfolderNewClass zipzapc
#pragma linkage(zipzapc, system)
#define M_zipzapfolderClassData zipzapd
#define M_zipzapfolderCClassData zipzapx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_zipzapfolder_classObj M_zipzapfolderClassData.classObject
#define _M_zipzapfolder M_zipzapfolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_zipzapfolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_zipzapfolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_zipzapfolderClassDataStructure {
	SOMClass *classObject;
	somMToken _get_hmodResource;
	somMToken _set_hmodResource;
	somMToken _get_hMyIcon;
	somMToken _set_hMyIcon;
} SOMDLINK M_zipzapfolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_zipzapfolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_zipzapfolderCClassData;

/*
 * New and Renew macros for M_zipzapfolder
 */
#define M_zipzapfolderNew() \
   (_somNew(_M_zipzapfolder ? _M_zipzapfolder : M_zipzapfolderNewClass(M_zipzapfolder_MajorVersion, M_zipzapfolder_MinorVersion)))
#define M_zipzapfolderRenew(buf) \
   (_somRenew(_M_zipzapfolder ? _M_zipzapfolder : M_zipzapfolderNewClass(M_zipzapfolder_MajorVersion, M_zipzapfolder_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_zipzapfolder_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_zipzapfolder_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_zipzapfolder_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_zipzapfolder_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_zipzapfolder_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_zipzapfolder_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_zipzapfolder_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_zipzapfolder_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_zipzapfolder_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_zipzapfolder_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_zipzapfolder_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_zipzapfolder_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_zipzapfolder_wpclsNew M_WPObject_wpclsNew
#define M_zipzapfolder_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_zipzapfolder_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_zipzapfolder_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_zipzapfolder_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_zipzapfolder_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_zipzapfolder_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_zipzapfolder_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_zipzapfolder_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_zipzapfolder_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_zipzapfolder_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_zipzapfolder_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_zipzapfolder_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_zipzapfolder_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_zipzapfolder_wpclsSetError M_WPObject_wpclsSetError
#define M_zipzapfolder_wpclsQueryError M_WPObject_wpclsQueryError
#define M_zipzapfolder_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_zipzapfolder_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_zipzapfolder_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_zipzapfolder_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_zipzapfolder_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_zipzapfolder_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_zipzapfolder_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_zipzapfolder_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_zipzapfolder_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_zipzapfolder_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_zipzapfolder_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_zipzapfolder_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_zipzapfolder_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_zipzapfolder__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_zipzapfolder__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_zipzapfolder__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_zipzapfolder__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_zipzapfolder_somNew SOMClass_somNew
#define M_zipzapfolder_somNewNoInit SOMClass_somNewNoInit
#define M_zipzapfolder_somRenew SOMClass_somRenew
#define M_zipzapfolder_somRenewNoInit SOMClass_somRenewNoInit
#define M_zipzapfolder_somRenewNoZero SOMClass_somRenewNoZero
#define M_zipzapfolder_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_zipzapfolder_somAllocate SOMClass_somAllocate
#define M_zipzapfolder_somDeallocate SOMClass_somDeallocate
#define M_zipzapfolder__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_zipzapfolder__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_zipzapfolder_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_zipzapfolder_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_zipzapfolder_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_zipzapfolder_somInitClass SOMClass_somInitClass
#define M_zipzapfolder_somInitMIClass SOMClass_somInitMIClass
#define M_zipzapfolder_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_zipzapfolder_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_zipzapfolder_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_zipzapfolder_somClassReady SOMClass_somClassReady
#define M_zipzapfolder_somGetApplyStub SOMClass_somGetApplyStub
#define M_zipzapfolder_somGetClassData SOMClass_somGetClassData
#define M_zipzapfolder_somSetClassData SOMClass_somSetClassData
#define M_zipzapfolder_somGetClassMtab SOMClass_somGetClassMtab
#define M_zipzapfolder_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_zipzapfolder_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_zipzapfolder_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_zipzapfolder_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_zipzapfolder_somGetMemberToken SOMClass_somGetMemberToken
#define M_zipzapfolder_somGetMethodData SOMClass_somGetMethodData
#define M_zipzapfolder_somGetRdStub SOMClass_somGetRdStub
#define M_zipzapfolder_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_zipzapfolder_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_zipzapfolder_somGetMethodToken SOMClass_somGetMethodToken
#define M_zipzapfolder_somGetName SOMClass_somGetName
#define M_zipzapfolder_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_zipzapfolder_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_zipzapfolder_somGetNumMethods SOMClass_somGetNumMethods
#define M_zipzapfolder_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_zipzapfolder_somGetParent SOMClass_somGetParent
#define M_zipzapfolder_somGetParents SOMClass_somGetParents
#define M_zipzapfolder_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_zipzapfolder_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_zipzapfolder_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_zipzapfolder_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_zipzapfolder_somFindMethod SOMClass_somFindMethod
#define M_zipzapfolder_somFindMethodOk SOMClass_somFindMethodOk
#define M_zipzapfolder_somFindSMethod SOMClass_somFindSMethod
#define M_zipzapfolder_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_zipzapfolder_somLookupMethod SOMClass_somLookupMethod
#define M_zipzapfolder_somCheckVersion SOMClass_somCheckVersion
#define M_zipzapfolder_somDescendedFrom SOMClass_somDescendedFrom
#define M_zipzapfolder_somSupportsMethod SOMClass_somSupportsMethod
#define M_zipzapfolder_somDefinedMethod SOMClass_somDefinedMethod
#define M_zipzapfolder_somOverrideMtab SOMClass_somOverrideMtab
#define M_zipzapfolder_somDefaultInit SOMObject_somDefaultInit
#define M_zipzapfolder_somDestruct SOMObject_somDestruct
#define M_zipzapfolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_zipzapfolder_somDefaultAssign SOMObject_somDefaultAssign
#define M_zipzapfolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_zipzapfolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_zipzapfolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_zipzapfolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_zipzapfolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_zipzapfolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_zipzapfolder_somInit SOMObject_somInit
#define M_zipzapfolder_somFree SOMObject_somFree
#define M_zipzapfolder_somUninit SOMObject_somUninit
#define M_zipzapfolder_somGetClass SOMObject_somGetClass
#define M_zipzapfolder_somGetClassName SOMObject_somGetClassName
#define M_zipzapfolder_somGetSize SOMObject_somGetSize
#define M_zipzapfolder_somIsA SOMObject_somIsA
#define M_zipzapfolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_zipzapfolder_somRespondsTo SOMObject_somRespondsTo
#define M_zipzapfolder_somDispatch SOMObject_somDispatch
#define M_zipzapfolder_somClassDispatch SOMObject_somClassDispatch
#define M_zipzapfolder_somCastObj SOMObject_somCastObj
#define M_zipzapfolder_somResetObj SOMObject_somResetObj
#define M_zipzapfolder_somDispatchV SOMObject_somDispatchV
#define M_zipzapfolder_somDispatchL SOMObject_somDispatchL
#define M_zipzapfolder_somDispatchA SOMObject_somDispatchA
#define M_zipzapfolder_somDispatchD SOMObject_somDispatchD
#define M_zipzapfolder_somPrintSelf SOMObject_somPrintSelf
#define M_zipzapfolder_somDumpSelf SOMObject_somDumpSelf
#define M_zipzapfolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_zipzapfolder_h */
